apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: snap-report-backend-mysql-connection
  namespace: snap-report
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  data:
  - secretKey: MYSQL_ROOT_PASSWORD
    remoteRef:
      key: mysql
      property: root-pasword
  - secretKey: MYSQL_PASSWORD
    remoteRef:
      key: mysql
      property: user-pasword
  - secretKey: MYSQL_DATABASE
    remoteRef:
      key: mysql
      property: database
  - secretKey: MYSQL_USER
    remoteRef:
      key: mysql
      property: username
