apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-issuer
  labels:
    app: snap-report-mysql
  name: mysql
  namespace: snap-report
spec:
  ingressClassName: nginx
  rules:
  - host: mysql.snap-ci.ovh
    http:
      paths:
      - backend:
          service:
            name: snap-report-mysql
            port:
              number: 3306
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - mysql.snap-ci.ovh
    secretName: mysql.snap-ci.ovh-tls