apiVersion: v1
kind: Service
metadata:
  name: snap-report-mysql
  namespace: snap-report
spec:
  selector:
    app: snap-report-mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  type: LoadBalancer