apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: snap-report
  labels:
    app: mysql
    version: "5.7"
data:
  my.cnf: |
    [mysqld]
    max_connections = 600
    read_buffer_size = 1048576
    net_read_timeout = 360
    net_write_timeout = 360